# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielistview', '0002_auto_20170519_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tomatometer',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
