# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 05:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movielistview', '0004_auto_20170522_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_read_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='movie',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
