# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielistview', '0005_auto_20170522_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_read_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
