# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielistview', '0006_auto_20170522_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='key',
            field=models.CharField(default='*', max_length=5000, unique=True),
        ),
    ]
