# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movielistview', '0007_auto_20170522_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_read',
            new_name='show_read',
        ),
    ]
